import type { Knex } from "knex";


export async function up(knex: Knex): Promise<void> {
    await knex.raw(`
    ALTER TABLE customer_address
    ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY;`)
}


export async function down(knex: Knex): Promise<void> {
    await knex.raw(`
    ALTER TABLE customer_address
    ALTER COLUMN id
     DROP IDENTITY ;    `)
}

